name: ASDF CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  plugin-test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        version:
          - "1.11.0"
          - "1.14.0"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: container-structure-test version
          version: ${{ matrix.version }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run ShellCheck
        run: shellcheck bin/*
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install prettier and sh plugin
        run: npm install -g prettier prettier-plugin-sh
      - name: Run prettier
        run: prettier --check .
      - name: Run prettier on bin
        run: prettier --check --parser sh 'bin/**'
